
// this file is generated — do not edit it


/// <reference types="@sveltejs/kit" />

/**
 * Environment variables [loaded by Vite](https://vitejs.dev/guide/env-and-mode.html#env-files) from `.env` files and `process.env`. Like [`$env/dynamic/private`](https://kit.svelte.dev/docs/modules#$env-dynamic-private), this module cannot be imported into client-side code. This module only includes variables that _do not_ begin with [`config.kit.env.publicPrefix`](https://kit.svelte.dev/docs/configuration#env) _and do_ start with [`config.kit.env.privatePrefix`](https://kit.svelte.dev/docs/configuration#env) (if configured).
 * 
 * _Unlike_ [`$env/dynamic/private`](https://kit.svelte.dev/docs/modules#$env-dynamic-private), the values exported from this module are statically injected into your bundle at build time, enabling optimisations like dead code elimination.
 * 
 * ```ts
 * import { API_KEY } from '$env/static/private';
 * ```
 * 
 * Note that all environment variables referenced in your code should be declared (for example in an `.env` file), even if they don't have a value until the app is deployed:
 * 
 * ```
 * MY_FEATURE_FLAG=""
 * ```
 * 
 * You can override `.env` values from the command line like so:
 * 
 * ```bash
 * MY_FEATURE_FLAG="enabled" npm run dev
 * ```
 */
declare module '$env/static/private' {
	export const AUTOJUMP_ERROR_PATH: string;
	export const NVM_INC: string;
	export const npm_package_exports___Et_svelte_types: string;
	export const npm_package_exports___Et_svelte_svelte: string;
	export const npm_package_exports___FrBre_svelte_types: string;
	export const npm_package_exports___FrBre_svelte_svelte: string;
	export const npm_package_exports___Sv_svelte_types: string;
	export const npm_package_exports___Sv_svelte_svelte: string;
	export const npm_package_exports___UsAl_svelte_types: string;
	export const npm_package_exports___UsAl_svelte_svelte: string;
	export const STARSHIP_SHELL: string;
	export const npm_package_devDependencies_prettier: string;
	export const npm_package_exports___Au_svelte_svelte: string;
	export const npm_package_exports___Bl_svelte_svelte: string;
	export const npm_package_exports___Cy_svelte_types: string;
	export const npm_package_exports___Dz_svelte_svelte: string;
	export const npm_package_exports___Gm_svelte_types: string;
	export const npm_package_exports___Hn_svelte_svelte: string;
	export const npm_package_exports___Lb_svelte_svelte: string;
	export const npm_package_exports___Malayali_svelte_types: string;
	export const npm_package_exports___Ms_svelte_types: string;
	export const npm_package_exports___Olympics_svelte_types: string;
	export const npm_package_exports___PkSd_svelte_svelte: string;
	export const npm_package_exports___Pt_svelte_types: string;
	export const npm_package_exports___Pt20_svelte_svelte: string;
	export const npm_package_exports___Sk_svelte_svelte: string;
	export const npm_package_exports___Th_svelte_types: string;
	export const npm_package_exports___Uy_svelte_svelte: string;
	export const npm_package_exports___Ar_svelte_svelte: string;
	export const npm_package_exports___Bs_svelte_types: string;
	export const npm_package_exports___De_svelte_types: string;
	export const npm_package_exports___EcW_svelte_svelte: string;
	export const npm_package_exports___EsVariant_svelte_svelte: string;
	export const npm_package_exports___RuDpr_svelte_types: string;
	export const npm_package_exports___RuKo_svelte_svelte: string;
	export const npm_package_exports___ShAc_svelte_svelte: string;
	export const npm_package_exports___ShHl_svelte_svelte: string;
	export const npm_package_exports___Sl_svelte_svelte: string;
	export const npm_package_exports___St_svelte_types: string;
	export const TERM_PROGRAM: string;
	export const npm_package_devDependencies_eslint_plugin_svelte: string;
	export const npm_package_exports___Aw_svelte_svelte: string;
	export const npm_package_exports___Bn_svelte_svelte: string;
	export const npm_package_exports___Earth_svelte_types: string;
	export const npm_package_exports___EsCe_svelte_svelte: string;
	export const npm_package_exports___Lv_svelte_types: string;
	export const npm_package_exports___Si_svelte_svelte: string;
	export const npm_package_exports___Soviet_union_svelte_types: string;
	export const npm_package_exports___UsGa_svelte_svelte: string;
	export const NODE: string;
	export const npm_package_exports___Ad_svelte_types: string;
	export const npm_package_exports___Ad_svelte_svelte: string;
	export const npm_package_exports___Dk_svelte_types: string;
	export const npm_package_exports___Dk_svelte_svelte: string;
	export const npm_package_exports___European_union_svelte_types: string;
	export const npm_package_exports___European_union_svelte_svelte: string;
	export const npm_package_exports___Ls_svelte_types: string;
	export const npm_package_exports___Ls_svelte_svelte: string;
	export const npm_package_exports___Sz_svelte_types: string;
	export const npm_package_exports___Sz_svelte_svelte: string;
	export const npm_package_exports___UsRi_svelte_types: string;
	export const npm_package_exports___UsRi_svelte_svelte: string;
	export const npm_package_exports___Va_svelte_types: string;
	export const npm_package_exports___Va_svelte_svelte: string;
	export const AUTOJUMP_SOURCED: string;
	export const INIT_CWD: string;
	export const NVM_CD_FLAGS: string;
	export const TURBO_INVOCATION_DIR: string;
	export const npm_package_homepage: string;
	export const npm_package_devDependencies_prettier_plugin_svelte: string;
	export const npm_package_devDependencies_typescript: string;
	export const npm_package_exports___Afar_svelte_types: string;
	export const npm_package_exports___AqTrue_south_svelte_types: string;
	export const npm_package_exports___Gi_svelte_types: string;
	export const npm_package_exports___Jp_svelte_svelte: string;
	export const npm_package_exports___Ke_svelte_types: string;
	export const npm_package_exports___Kg_svelte_svelte: string;
	export const npm_package_exports___Mu_svelte_svelte: string;
	export const npm_package_exports___Mw_svelte_types: string;
	export const npm_package_exports___Nl_svelte_svelte: string;
	export const npm_package_exports___Pr_svelte_svelte: string;
	export const npm_package_exports___Qa_svelte_svelte: string;
	export const npm_package_exports___Tl_svelte_types: string;
	export const npm_package_exports___Tn_svelte_svelte: string;
	export const npm_package_exports___UsMs_svelte_types: string;
	export const npm_package_exports___UsTx_svelte_types: string;
	export const SHELL: string;
	export const TERM: string;
	export const WARP_HONOR_PS1: string;
	export const npm_package_devDependencies_vite: string;
	export const npm_package_exports___CaBc_svelte_svelte: string;
	export const npm_package_exports___Cx_svelte_types: string;
	export const npm_package_exports___EsIb_svelte_svelte: string;
	export const npm_package_exports___Gl_svelte_types: string;
	export const npm_package_exports___Gt_svelte_svelte: string;
	export const npm_package_exports___Jo_svelte_svelte: string;
	export const npm_package_exports___Mr_svelte_types: string;
	export const npm_package_exports___Northern_cyprus_svelte_svelte: string;
	export const npm_package_exports___Pm_svelte_svelte: string;
	export const npm_package_devDependencies_svelte_lib_helpers: string;
	export const npm_package_exports___AfEmirate_svelte_svelte: string;
	export const npm_package_exports___As_svelte_svelte: string;
	export const npm_package_exports___AuAboriginal_svelte_types: string;
	export const npm_package_exports___Bd_svelte_types: string;
	export const npm_package_exports___Bj_svelte_svelte: string;
	export const npm_package_exports___GbNir_svelte_svelte: string;
	export const npm_package_exports___InGj_svelte_types: string;
	export const npm_package_exports___InOr_svelte_types: string;
	export const npm_package_exports___NlFr_svelte_types: string;
	export const npm_package_exports___Sc_svelte_types: string;
	export const npm_package_exports___Sm_svelte_svelte: string;
	export const npm_package_exports___Xx_svelte_svelte: string;
	export const npm_package_exports___Ye_svelte_types: string;
	export const TMPDIR: string;
	export const npm_package_exports___Bi_svelte_svelte: string;
	export const npm_package_exports___Cn_svelte_types: string;
	export const npm_package_exports___Hk_svelte_svelte: string;
	export const npm_package_exports___Md_svelte_types: string;
	export const npm_package_exports___RuCu_svelte_types: string;
	export const npm_package_exports___Sn_svelte_svelte: string;
	export const npm_package_exports___Vu_svelte_svelte: string;
	export const npm_package_exports___Za_svelte_svelte: string;
	export const npm_package_scripts_lint: string;
	export const npm_package_exports___Ao_svelte_types: string;
	export const npm_package_exports___AuAboriginal_svelte_svelte: string;
	export const npm_package_exports___AuAct_svelte_types: string;
	export const npm_package_exports___Bd_svelte_svelte: string;
	export const npm_package_exports___Es_svelte_types: string;
	export const npm_package_exports___Hausa_svelte_types: string;
	export const npm_package_exports___Ht_svelte_types: string;
	export const npm_package_exports___InGj_svelte_svelte: string;
	export const npm_package_exports___InMz_svelte_types: string;
	export const npm_package_exports___InOr_svelte_svelte: string;
	export const npm_package_exports___NlFr_svelte_svelte: string;
	export const npm_package_exports___Om_svelte_types: string;
	export const npm_package_exports___Otomi_svelte_types: string;
	export const npm_package_exports___Sc_svelte_svelte: string;
	export const npm_package_exports___South_ossetia_svelte_types: string;
	export const npm_package_exports___UsAk_svelte_types: string;
	export const npm_package_exports___Ye_svelte_svelte: string;
	export const TERM_PROGRAM_VERSION: string;
	export const npm_package_exports___Dm_svelte_types: string;
	export const npm_package_exports___FrCp_svelte_svelte: string;
	export const npm_package_exports___GbSct_svelte_types: string;
	export const npm_package_exports___Ir_svelte_svelte: string;
	export const npm_package_exports___Lu_svelte_types: string;
	export const npm_package_exports___Ng_svelte_svelte: string;
	export const npm_package_exports___Pt30_svelte_svelte: string;
	export const npm_package_exports___Py_svelte_svelte: string;
	export const npm_package_exports___RuLpr_svelte_types: string;
	export const npm_package_exports___UsNc_svelte_svelte: string;
	export const npm_package_exports___Vg_svelte_types: string;
	export const npm_package_scripts_dev: string;
	export const npm_package_devDependencies_postcss_load_config: string;
	export const npm_package_exports___AuNsw_svelte_svelte: string;
	export const npm_package_exports___AuWa_svelte_types: string;
	export const npm_package_exports___Bf_svelte_svelte: string;
	export const npm_package_exports___Cw_svelte_types: string;
	export const npm_package_exports___Ec_svelte_svelte: string;
	export const npm_package_exports___Fj_svelte_svelte: string;
	export const npm_package_exports___Iq_svelte_types: string;
	export const npm_package_exports___Maori_svelte_svelte: string;
	export const npm_package_exports___Nato_svelte_svelte: string;
	export const npm_package_exports___Quechua_svelte_types: string;
	export const npm_package_exports___Sa_svelte_svelte: string;
	export const npm_package_exports___Somaliland_svelte_types: string;
	export const npm_package_exports___Tf_svelte_types: string;
	export const npm_package_exports___Us_svelte_svelte: string;
	export const npm_package_exports___Ws_svelte_types: string;
	export const MallocNanoZone: string;
	export const ORIGINAL_XDG_CURRENT_DESKTOP: string;
	export const ZDOTDIR: string;
	export const npm_package_scripts_prepublishOnly: string;
	export const npm_package_exports___Al_svelte_svelte: string;
	export const npm_package_exports___Be_svelte_types: string;
	export const npm_package_exports___EsCn_svelte_types: string;
	export const npm_package_exports___EsMl_svelte_types: string;
	export const npm_package_exports___Fi_svelte_types: string;
	export const npm_package_exports___Icon_svelte_types: string;
	export const npm_package_exports___Lk_svelte_types: string;
	export const npm_package_exports___Re_svelte_svelte: string;
	export const npm_package_exports___Ru_svelte_types: string;
	export const npm_package_exports___Sb_svelte_types: string;
	export const npm_package_exports___Sr_svelte_svelte: string;
	export const npm_package_exports___Vi_svelte_svelte: string;
	export const npm_package_exports___Yt_svelte_svelte: string;
	export const npm_package_exports___Zm_svelte_types: string;
	export const npm_package_exports___AuTas_svelte_types: string;
	export const npm_package_exports___AuWa_svelte_svelte: string;
	export const npm_package_exports___Br_svelte_types: string;
	export const npm_package_exports___Cw_svelte_svelte: string;
	export const npm_package_exports___East_african_federation_svelte_types: string;
	export const npm_package_exports___Iq_svelte_svelte: string;
	export const npm_package_exports___Quechua_svelte_svelte: string;
	export const npm_package_exports___Somaliland_svelte_svelte: string;
	export const npm_package_exports___Tf_svelte_svelte: string;
	export const npm_package_exports___Tibet_svelte_types: string;
	export const npm_package_exports___Ug_svelte_types: string;
	export const npm_package_exports___Vn_svelte_types: string;
	export const npm_package_exports___Ws_svelte_svelte: string;
	export const npm_package_devDependencies__sveltejs_kit: string;
	export const npm_package_devDependencies_svelte_preprocess: string;
	export const npm_package_exports___svelte: string;
	export const npm_package_exports___Bo_svelte_svelte: string;
	export const npm_package_exports___CaBc_svelte_types: string;
	export const npm_package_exports___EsIb_svelte_types: string;
	export const npm_package_exports___Gt_svelte_types: string;
	export const npm_package_exports___Jo_svelte_types: string;
	export const npm_package_exports___La_svelte_svelte: string;
	export const npm_package_exports___Northern_cyprus_svelte_types: string;
	export const npm_package_exports___Pm_svelte_types: string;
	export const npm_package_exports___UsAr_svelte_svelte: string;
	export const npm_package_exports___Uz_svelte_svelte: string;
	export const npm_config_registry: string;
	export const ZSH: string;
	export const npm_package_devDependencies__floating_ui_dom: string;
	export const npm_package_repository_url: string;
	export const npm_package_exports___AuSa_svelte_types: string;
	export const npm_package_exports___AuVic_svelte_types: string;
	export const npm_package_exports___Bb_svelte_svelte: string;
	export const npm_package_exports___Eg_svelte_svelte: string;
	export const npm_package_exports___InMn_svelte_svelte: string;
	export const npm_package_exports___InTg_svelte_types: string;
	export const npm_package_exports___Mq_svelte_types: string;
	export const npm_package_exports___RuBa_svelte_svelte: string;
	export const npm_package_exports___Se_svelte_svelte: string;
	export const npm_package_exports___Tj_svelte_types: string;
	export const npm_package_exports___Transnistria_svelte_svelte: string;
	export const npm_package_exports___Cv_svelte_types: string;
	export const npm_package_exports___Cv_svelte_svelte: string;
	export const npm_package_exports___Gb_svelte_types: string;
	export const npm_package_exports___Gb_svelte_svelte: string;
	export const npm_package_exports___GbWls_svelte_types: string;
	export const npm_package_exports___GbWls_svelte_svelte: string;
	export const npm_package_exports___Kn_svelte_types: string;
	export const npm_package_exports___Kn_svelte_svelte: string;
	export const npm_package_exports___MqOld_svelte_types: string;
	export const npm_package_exports___MqOld_svelte_svelte: string;
	export const npm_package_exports___Ne_svelte_types: string;
	export const npm_package_exports___Ne_svelte_svelte: string;
	export const npm_package_exports___Tg_svelte_types: string;
	export const npm_package_exports___Tg_svelte_svelte: string;
	export const npm_package_exports___UsDc_svelte_types: string;
	export const npm_package_exports___UsDc_svelte_svelte: string;
	export const NVM_DIR: string;
	export const USER: string;
	export const npm_package_description: string;
	export const npm_package_exports___Ae_svelte_svelte: string;
	export const npm_package_exports___CaQc_svelte_types: string;
	export const npm_package_exports___ChGr_svelte_svelte: string;
	export const npm_package_exports___Ci_svelte_types: string;
	export const npm_package_exports___Dj_svelte_svelte: string;
	export const npm_package_exports___Easter_island_svelte_types: string;
	export const npm_package_exports___EtOr_svelte_types: string;
	export const npm_package_exports___Fr20r_svelte_svelte: string;
	export const npm_package_exports___Io_svelte_types: string;
	export const npm_package_exports___Lr_svelte_svelte: string;
	export const npm_package_exports___Mc_svelte_types: string;
	export const npm_package_exports___Nz_svelte_types: string;
	export const npm_package_exports___Wiphala_svelte_svelte: string;
	export const LS_COLORS: string;
	export const npm_package_license: string;
	export const npm_package_scripts_check_watch: string;
	export const npm_package_exports___Dm_svelte_svelte: string;
	export const npm_package_exports___FrCp_svelte_types: string;
	export const npm_package_exports___GbSct_svelte_svelte: string;
	export const npm_package_exports___Ir_svelte_types: string;
	export const npm_package_exports___Lu_svelte_svelte: string;
	export const npm_package_exports___Ng_svelte_types: string;
	export const npm_package_exports___Pt30_svelte_types: string;
	export const npm_package_exports___Py_svelte_types: string;
	export const npm_package_exports___RuLpr_svelte_svelte: string;
	export const npm_package_exports___UsNc_svelte_types: string;
	export const npm_package_exports___Vg_svelte_svelte: string;
	export const COMMAND_MODE: string;
	export const npm_package_devDependencies_mdsvex: string;
	export const npm_package_exports___Ag_svelte_svelte: string;
	export const npm_package_exports___AuNt_svelte_svelte: string;
	export const npm_package_exports___EsGa_svelte_svelte: string;
	export const npm_package_exports___Fr_svelte_svelte: string;
	export const npm_package_exports___Jp_svelte_types: string;
	export const npm_package_exports___Kg_svelte_types: string;
	export const npm_package_exports___Mu_svelte_types: string;
	export const npm_package_exports___Nl_svelte_types: string;
	export const npm_package_exports___Pr_svelte_types: string;
	export const npm_package_exports___Qa_svelte_types: string;
	export const npm_package_exports___RuUd_svelte_svelte: string;
	export const npm_package_exports___Sy_svelte_svelte: string;
	export const npm_package_exports___Tn_svelte_types: string;
	export const PNPM_SCRIPT_SRC_DIR: string;
	export const npm_package_exports___BqSe_svelte_types: string;
	export const npm_package_exports___BqSe_svelte_svelte: string;
	export const npm_package_exports___Cz_svelte_types: string;
	export const npm_package_exports___Cz_svelte_svelte: string;
	export const npm_package_exports___GbEng_svelte_types: string;
	export const npm_package_exports___GbEng_svelte_svelte: string;
	export const npm_package_exports___Gn_svelte_types: string;
	export const npm_package_exports___Gn_svelte_svelte: string;
	export const npm_package_exports___Mp_svelte_types: string;
	export const npm_package_exports___Mp_svelte_svelte: string;
	export const npm_package_exports___Ni_svelte_types: string;
	export const npm_package_exports___Ni_svelte_svelte: string;
	export const npm_package_exports___Occitania_svelte_types: string;
	export const npm_package_exports___Occitania_svelte_svelte: string;
	export const npm_package_exports___Pw_svelte_types: string;
	export const npm_package_exports___Pw_svelte_svelte: string;
	export const npm_package_exports___Tk_svelte_types: string;
	export const npm_package_exports___Tk_svelte_svelte: string;
	export const npm_package_exports___UsNm_svelte_types: string;
	export const npm_package_exports___UsNm_svelte_svelte: string;
	export const npm_package_exports___Cm_svelte_types: string;
	export const npm_package_exports___Co_svelte_svelte: string;
	export const npm_package_exports___EsPv_svelte_svelte: string;
	export const npm_package_exports___Gy_svelte_types: string;
	export const npm_package_exports___Kw_svelte_svelte: string;
	export const npm_package_exports___Me_svelte_svelte: string;
	export const npm_package_exports___Mg_svelte_types: string;
	export const npm_package_exports___RuDa_svelte_svelte: string;
	export const npm_package_exports___UsCa_svelte_types: string;
	export const SSH_AUTH_SOCK: string;
	export const npm_package_exports___Bg_svelte_svelte: string;
	export const npm_package_exports___Ch_svelte_types: string;
	export const npm_package_exports___EsAr_svelte_types: string;
	export const npm_package_exports___Fk_svelte_svelte: string;
	export const npm_package_exports___GbOrk_svelte_types: string;
	export const npm_package_exports___GeAb_svelte_types: string;
	export const npm_package_exports___IdJt_svelte_types: string;
	export const npm_package_exports___In_svelte_types: string;
	export const npm_package_exports___Kp_svelte_types: string;
	export const npm_package_exports___Li_svelte_svelte: string;
	export const npm_package_exports___Pe_svelte_types: string;
	export const npm_package_exports___Rw_svelte_svelte: string;
	export const npm_package_exports___UsAz_svelte_svelte: string;
	export const npm_package_exports___UsHi_svelte_types: string;
	export const WARP_IS_LOCAL_SHELL_SESSION: string;
	export const __CF_USER_TEXT_ENCODING: string;
	export const npm_package_devDependencies_eslint: string;
	export const npm_package_devDependencies_postcss: string;
	export const npm_package_exports___Am_svelte_types: string;
	export const npm_package_exports___Bt_svelte_types: string;
	export const npm_package_exports___Bz_svelte_svelte: string;
	export const npm_package_exports___Lt_svelte_svelte: string;
	export const npm_package_exports___ShTa_svelte_svelte: string;
	export const npm_package_exports___Ss_svelte_types: string;
	export const npm_package_exports___Ua_svelte_types: string;
	export const npm_package_exports___UsFl_svelte_types: string;
	export const npm_package_exports___Yu_svelte_types: string;
	export const npm_package_devDependencies__typescript_eslint_eslint_plugin: string;
	export const npm_package_devDependencies_tslib: string;
	export const npm_package_exports___Bi_svelte_types: string;
	export const npm_package_exports___By_svelte_svelte: string;
	export const npm_package_exports___Do_svelte_svelte: string;
	export const npm_package_exports___Hk_svelte_types: string;
	export const npm_package_exports___Sn_svelte_types: string;
	export const npm_package_exports___Ve_svelte_svelte: string;
	export const npm_package_exports___Vu_svelte_types: string;
	export const npm_package_exports___Xk_svelte_svelte: string;
	export const npm_package_exports___Za_svelte_types: string;
	export const npm_execpath: string;
	export const PAGER: string;
	export const WARP_USE_SSH_WRAPPER: string;
	export const npm_package_devDependencies_svelte: string;
	export const npm_package_devDependencies_svelte_meta_tags: string;
	export const npm_package_exports___Am_svelte_svelte: string;
	export const npm_package_exports___Bt_svelte_svelte: string;
	export const npm_package_exports___Cq_svelte_types: string;
	export const npm_package_exports___Ge_svelte_types: string;
	export const npm_package_exports___Ki_svelte_types: string;
	export const npm_package_exports___Ss_svelte_svelte: string;
	export const npm_package_exports___Ua_svelte_svelte: string;
	export const npm_package_exports___UsFl_svelte_svelte: string;
	export const npm_package_exports___Yu_svelte_svelte: string;
	export const npm_package_author_name: string;
	export const npm_package_exports___Cd_svelte_svelte: string;
	export const npm_package_exports___CnXj_svelte_types: string;
	export const npm_package_exports___Gh_svelte_types: string;
	export const npm_package_exports___Gp_svelte_svelte: string;
	export const npm_package_exports___InAs_svelte_types: string;
	export const npm_package_exports___InKa_svelte_types: string;
	export const npm_package_exports___IqKr_svelte_types: string;
	export const npm_package_exports___Mn_svelte_svelte: string;
	export const npm_package_exports___Mv_svelte_types: string;
	export const npm_package_exports___No_svelte_types: string;
	export const npm_package_exports___Tm_svelte_types: string;
	export const npm_package_exports___UsIn_svelte_types: string;
	export const LSCOLORS: string;
	export const npm_package_exports___Ao_svelte_svelte: string;
	export const npm_package_exports___AuAct_svelte_svelte: string;
	export const npm_package_exports___Cg_svelte_types: string;
	export const npm_package_exports___Es_svelte_svelte: string;
	export const npm_package_exports___Gs_svelte_types: string;
	export const npm_package_exports___Hausa_svelte_svelte: string;
	export const npm_package_exports___Ht_svelte_svelte: string;
	export const npm_package_exports___InMz_svelte_svelte: string;
	export const npm_package_exports___Mm_svelte_types: string;
	export const npm_package_exports___Om_svelte_svelte: string;
	export const npm_package_exports___Otomi_svelte_svelte: string;
	export const npm_package_exports___South_ossetia_svelte_svelte: string;
	export const npm_package_exports___Tv_svelte_types: string;
	export const npm_package_exports___UsAk_svelte_svelte: string;
	export const npm_config_frozen_lockfile: string;
	export const npm_package_devDependencies__typescript_eslint_parser: string;
	export const npm_package_exports___Al_svelte_types: string;
	export const npm_package_exports___Cr_svelte_svelte: string;
	export const npm_package_exports___Ewe_svelte_svelte: string;
	export const npm_package_exports___Gf_svelte_svelte: string;
	export const npm_package_exports___Guarani_svelte_svelte: string;
	export const npm_package_exports___InTn_svelte_svelte: string;
	export const npm_package_exports___It_svelte_svelte: string;
	export const npm_package_exports___Mx_svelte_svelte: string;
	export const npm_package_exports___Na_svelte_svelte: string;
	export const npm_package_exports___Re_svelte_types: string;
	export const npm_package_exports___Sr_svelte_types: string;
	export const npm_package_exports___Tc_svelte_svelte: string;
	export const npm_package_exports___Vi_svelte_types: string;
	export const npm_package_exports___Yt_svelte_types: string;
	export const PATH: string;
	export const npm_package_exports___Cg_svelte_svelte: string;
	export const npm_package_exports___Cu_svelte_types: string;
	export const npm_package_exports___Ga_svelte_types: string;
	export const npm_package_exports___Gs_svelte_svelte: string;
	export const npm_package_exports___Is_svelte_types: string;
	export const npm_package_exports___Km_svelte_types: string;
	export const npm_package_exports___Mm_svelte_svelte: string;
	export const npm_package_exports___Nf_svelte_types: string;
	export const npm_package_exports___Td_svelte_types: string;
	export const npm_package_exports___Tv_svelte_svelte: string;
	export const npm_package_exports___Af_svelte_svelte: string;
	export const npm_package_exports___Bg_svelte_types: string;
	export const npm_package_exports___EsCt_svelte_svelte: string;
	export const npm_package_exports___Fk_svelte_types: string;
	export const npm_package_exports___Li_svelte_types: string;
	export const npm_package_exports___Ro_svelte_svelte: string;
	export const npm_package_exports___Rw_svelte_types: string;
	export const npm_package_exports___Sx_svelte_svelte: string;
	export const npm_package_exports___UsAz_svelte_types: string;
	export const npm_package_exports___Vc_svelte_svelte: string;
	export const npm_package_exports___Zw_svelte_svelte: string;
	export const LaunchInstanceID: string;
	export const npm_package_exports___AuTas_svelte_svelte: string;
	export const npm_package_exports___Br_svelte_svelte: string;
	export const npm_package_exports___Ck_svelte_types: string;
	export const npm_package_exports___East_african_federation_svelte_svelte: string;
	export const npm_package_exports___Im_svelte_types: string;
	export const npm_package_exports___Ma_svelte_types: string;
	export const npm_package_exports___Pf_svelte_types: string;
	export const npm_package_exports___PkJk_svelte_types: string;
	export const npm_package_exports___Tibet_svelte_svelte: string;
	export const npm_package_exports___Tz_svelte_types: string;
	export const npm_package_exports___Ug_svelte_svelte: string;
	export const npm_package_exports___UsTn_svelte_types: string;
	export const npm_package_exports___Vn_svelte_svelte: string;
	export const npm_config_engine_strict: string;
	export const USER_ZDOTDIR: string;
	export const __CFBundleIdentifier: string;
	export const npm_package_bugs: string;
	export const npm_package_keywords_4: string;
	export const npm_package_exports___Cf_svelte_types: string;
	export const npm_package_exports___Cf_svelte_svelte: string;
	export const npm_package_exports___Gr_svelte_types: string;
	export const npm_package_exports___Gr_svelte_svelte: string;
	export const npm_package_exports___Ml_svelte_types: string;
	export const npm_package_exports___Ml_svelte_svelte: string;
	export const npm_package_exports___Nu_svelte_types: string;
	export const npm_package_exports___Nu_svelte_svelte: string;
	export const npm_package_exports___Pk_svelte_types: string;
	export const npm_package_exports___Pk_svelte_svelte: string;
	export const npm_package_exports___Tw_svelte_types: string;
	export const npm_package_exports___Tw_svelte_svelte: string;
	export const PWD: string;
	export const npm_package_devDependencies_tailwindcss: string;
	export const npm_package_exports___AuSa_svelte_svelte: string;
	export const npm_package_exports___AuVic_svelte_svelte: string;
	export const npm_package_exports___Aw_svelte_types: string;
	export const npm_package_exports___Bn_svelte_types: string;
	export const npm_package_exports___EsCe_svelte_types: string;
	export const npm_package_exports___InTg_svelte_svelte: string;
	export const npm_package_exports___Mq_svelte_svelte: string;
	export const npm_package_exports___Si_svelte_types: string;
	export const npm_package_exports___Tj_svelte_svelte: string;
	export const npm_package_exports___UsGa_svelte_types: string;
	export const npm_command: string;
	export const npm_package_author_url: string;
	export const npm_package_scripts_preview: string;
	export const npm_package_devDependencies__sveltejs_package: string;
	export const npm_package_devDependencies_publint: string;
	export const npm_package_exports___Cd_svelte_types: string;
	export const npm_package_exports___CnXj_svelte_svelte: string;
	export const npm_package_exports___Gh_svelte_svelte: string;
	export const npm_package_exports___Gp_svelte_types: string;
	export const npm_package_exports___InAs_svelte_svelte: string;
	export const npm_package_exports___InKa_svelte_svelte: string;
	export const npm_package_exports___IqKr_svelte_svelte: string;
	export const npm_package_exports___Mn_svelte_types: string;
	export const npm_package_exports___Mv_svelte_svelte: string;
	export const npm_package_exports___No_svelte_svelte: string;
	export const npm_package_exports___Tm_svelte_svelte: string;
	export const npm_package_exports___UsIn_svelte_svelte: string;
	export const npm_package_exports___Co_svelte_types: string;
	export const npm_package_exports___Cy_svelte_svelte: string;
	export const npm_package_exports___EsPv_svelte_types: string;
	export const npm_package_exports___Gm_svelte_svelte: string;
	export const npm_package_exports___Kw_svelte_types: string;
	export const npm_package_exports___Malayali_svelte_svelte: string;
	export const npm_package_exports___Me_svelte_types: string;
	export const npm_package_exports___Ms_svelte_svelte: string;
	export const npm_package_exports___Olympics_svelte_svelte: string;
	export const npm_package_exports___Pt_svelte_svelte: string;
	export const npm_package_exports___RuDa_svelte_types: string;
	export const npm_package_exports___Th_svelte_svelte: string;
	export const npm_lifecycle_event: string;
	export const LANG: string;
	export const npm_package_name: string;
	export const npm_package_devDependencies__sveltejs_vite_plugin_svelte: string;
	export const npm_package_svelte: string;
	export const npm_package_types: string;
	export const npm_package_keywords_0: string;
	export const npm_package_repository_type: string;
	export const npm_package_exports___GbCon_svelte_types: string;
	export const npm_package_exports___GbCon_svelte_svelte: string;
	export const npm_package_exports___Il_svelte_types: string;
	export const npm_package_exports___Il_svelte_svelte: string;
	export const npm_package_exports___Je_svelte_types: string;
	export const npm_package_exports___Je_svelte_svelte: string;
	export const npm_package_exports___Kr_svelte_types: string;
	export const npm_package_exports___Kr_svelte_svelte: string;
	export const npm_package_exports___Mars_svelte_types: string;
	export const npm_package_exports___Mars_svelte_svelte: string;
	export const npm_package_exports___Pg_svelte_types: string;
	export const npm_package_exports___Pg_svelte_svelte: string;
	export const npm_package_exports___Yorubaland_svelte_types: string;
	export const npm_package_exports___Yorubaland_svelte_svelte: string;
	export const npm_package_scripts_test_integration: string;
	export const npm_package_keywords_1: string;
	export const npm_package_exports___AfEmirate_svelte_types: string;
	export const npm_package_exports___Aq_svelte_svelte: string;
	export const npm_package_exports___As_svelte_types: string;
	export const npm_package_exports___Bh_svelte_svelte: string;
	export const npm_package_exports___Bj_svelte_types: string;
	export const npm_package_exports___GbNir_svelte_types: string;
	export const npm_package_exports___RuTa_svelte_svelte: string;
	export const npm_package_exports___Sm_svelte_types: string;
	export const npm_package_exports___So_svelte_svelte: string;
	export const npm_package_exports___Torres_strait_islands_svelte_svelte: string;
	export const npm_package_exports___Xx_svelte_types: string;
	export const NODE_PATH: string;
	export const npm_package_scripts_build: string;
	export const npm_package_devDependencies_svelte_toc: string;
	export const npm_package_keywords_2: string;
	export const npm_package_exports___types: string;
	export const npm_package_exports___An_svelte_svelte: string;
	export const npm_package_exports___AuQld_svelte_svelte: string;
	export const npm_package_exports___Bo_svelte_types: string;
	export const npm_package_exports___Bw_svelte_svelte: string;
	export const npm_package_exports___Er_svelte_svelte: string;
	export const npm_package_exports___Hu_svelte_svelte: string;
	export const npm_package_exports___La_svelte_types: string;
	export const npm_package_exports___Ly_svelte_svelte: string;
	export const npm_package_exports___UsAr_svelte_types: string;
	export const npm_package_exports___Uz_svelte_types: string;
	export const TURBO_HASH: string;
	export const VSCODE_GIT_ASKPASS_EXTRA_ARGS: string;
	export const XPC_FLAGS: string;
	export const npm_package_devDependencies_vitest: string;
	export const npm_package_keywords_3: string;
	export const npm_package_exports___Afar_svelte_svelte: string;
	export const npm_package_exports___AqTrue_south_svelte_svelte: string;
	export const npm_package_exports___EtTi_svelte_types: string;
	export const npm_package_exports___Gg_svelte_types: string;
	export const npm_package_exports___Gi_svelte_svelte: string;
	export const npm_package_exports___Ke_svelte_svelte: string;
	export const npm_package_exports___Mw_svelte_svelte: string;
	export const npm_package_exports___My_svelte_types: string;
	export const npm_package_exports___Tl_svelte_svelte: string;
	export const npm_package_exports___UsMs_svelte_svelte: string;
	export const npm_package_exports___UsTx_svelte_svelte: string;
	export const npm_package_scripts_gen_compo_data: string;
	export const npm_package_devDependencies_flowbite_svelte: string;
	export const npm_package_exports___BqSa_svelte_svelte: string;
	export const npm_package_exports___By_svelte_types: string;
	export const npm_package_exports___Do_svelte_types: string;
	export const npm_package_exports___IdJb_svelte_svelte: string;
	export const npm_package_exports___Mt_svelte_svelte: string;
	export const npm_package_exports___Ps_svelte_svelte: string;
	export const npm_package_exports___RuCe_svelte_svelte: string;
	export const npm_package_exports___To_svelte_svelte: string;
	export const npm_package_exports___Ve_svelte_types: string;
	export const npm_package_exports___Xk_svelte_types: string;
	export const npm_package_devDependencies_tailwind_merge: string;
	export const npm_package_exports___Ca_svelte_types: string;
	export const npm_package_exports___EtTi_svelte_svelte: string;
	export const npm_package_exports___Gg_svelte_svelte: string;
	export const npm_package_exports___Gu_svelte_types: string;
	export const npm_package_exports___Kongo_svelte_types: string;
	export const npm_package_exports___Ky_svelte_types: string;
	export const npm_package_exports___Mk_svelte_types: string;
	export const npm_package_exports___My_svelte_svelte: string;
	export const npm_package_exports___Nr_svelte_types: string;
	export const npm_package_exports___Pl_svelte_types: string;
	export const npm_package_exports___UsMo_svelte_types: string;
	export const npm_package_main: string;
	export const npm_package_devDependencies_eslint_config_prettier: string;
	export const npm_package_exports___Az_svelte_svelte: string;
	export const npm_package_exports___Cl_svelte_types: string;
	export const npm_package_exports___Fo_svelte_svelte: string;
	export const npm_package_exports___Mf_svelte_types: string;
	export const npm_package_exports___Pa_svelte_types: string;
	export const npm_package_exports___Rs_svelte_svelte: string;
	export const npm_package_exports___Sd_svelte_svelte: string;
	export const npm_config_node_gyp: string;
	export const XPC_SERVICE_NAME: string;
	export const npm_package_version: string;
	export const npm_package_devDependencies__sveltejs_adapter_auto: string;
	export const npm_package_exports___BqBo_svelte_types: string;
	export const npm_package_exports___Cq_svelte_svelte: string;
	export const npm_package_exports___Ee_svelte_types: string;
	export const npm_package_exports___Ge_svelte_svelte: string;
	export const npm_package_exports___Ki_svelte_svelte: string;
	export const npm_package_exports___Sg_svelte_types: string;
	export const VSCODE_INJECTION: string;
	export const npm_package_devDependencies_autoprefixer: string;
	export const npm_package_devDependencies_svelte_check: string;
	export const npm_package_exports___Cr_svelte_types: string;
	export const npm_package_exports___Ewe_svelte_types: string;
	export const npm_package_exports___Gf_svelte_types: string;
	export const npm_package_exports___Guarani_svelte_types: string;
	export const npm_package_exports___Hmong_svelte_svelte: string;
	export const npm_package_exports___Id_svelte_svelte: string;
	export const npm_package_exports___InTn_svelte_types: string;
	export const npm_package_exports___It_svelte_types: string;
	export const npm_package_exports___Jm_svelte_svelte: string;
	export const npm_package_exports___Kz_svelte_svelte: string;
	export const npm_package_exports___Mh_svelte_svelte: string;
	export const npm_package_exports___Mx_svelte_types: string;
	export const npm_package_exports___Na_svelte_types: string;
	export const npm_package_exports___Tc_svelte_types: string;
	export const npm_package_exports___Wf_svelte_svelte: string;
	export const HOME: string;
	export const SHLVL: string;
	export const npm_package_type: string;
	export const npm_package_exports___BqBo_svelte_svelte: string;
	export const npm_package_exports___Ee_svelte_svelte: string;
	export const npm_package_exports___Gq_svelte_types: string;
	export const npm_package_exports___Kanuri_svelte_types: string;
	export const npm_package_exports___Mo_svelte_types: string;
	export const npm_package_exports___Ph_svelte_types: string;
	export const npm_package_exports___Sg_svelte_svelte: string;
	export const npm_package_exports___Tt_svelte_types: string;
	export const npm_package_exports___United_nations_svelte_types: string;
	export const VSCODE_GIT_ASKPASS_MAIN: string;
	export const npm_package_scripts_test: string;
	export const npm_package_exports___An_svelte_types: string;
	export const npm_package_exports___AuQld_svelte_types: string;
	export const npm_package_exports___Bw_svelte_types: string;
	export const npm_package_exports___Cx_svelte_svelte: string;
	export const npm_package_exports___Er_svelte_types: string;
	export const npm_package_exports___Gl_svelte_svelte: string;
	export const npm_package_exports___Hu_svelte_types: string;
	export const npm_package_exports___Ly_svelte_types: string;
	export const npm_package_exports___Mr_svelte_svelte: string;
	export const npm_package_exports___Au_svelte_types: string;
	export const npm_package_exports___Bl_svelte_types: string;
	export const npm_package_exports___Cu_svelte_svelte: string;
	export const npm_package_exports___Dz_svelte_types: string;
	export const npm_package_exports___Ga_svelte_svelte: string;
	export const npm_package_exports___Hn_svelte_types: string;
	export const npm_package_exports___Is_svelte_svelte: string;
	export const npm_package_exports___Km_svelte_svelte: string;
	export const npm_package_exports___Lb_svelte_types: string;
	export const npm_package_exports___Nf_svelte_svelte: string;
	export const npm_package_exports___PkSd_svelte_types: string;
	export const npm_package_exports___Pt20_svelte_types: string;
	export const npm_package_exports___Sk_svelte_types: string;
	export const npm_package_exports___Td_svelte_svelte: string;
	export const npm_package_exports___Uy_svelte_types: string;
	export const HOMEBREW_PREFIX: string;
	export const npm_package_scripts_gen_exports: string;
	export const npm_package_exports___Ax_svelte_types: string;
	export const npm_package_exports___Ax_svelte_svelte: string;
	export const npm_package_exports___Ba_svelte_types: string;
	export const npm_package_exports___Ba_svelte_svelte: string;
	export const npm_package_exports___Fm_svelte_types: string;
	export const npm_package_exports___Fm_svelte_svelte: string;
	export const npm_package_exports___Ag_svelte_types: string;
	export const npm_package_exports___AuNt_svelte_types: string;
	export const npm_package_exports___Ck_svelte_svelte: string;
	export const npm_package_exports___EsGa_svelte_types: string;
	export const npm_package_exports___Fr_svelte_types: string;
	export const npm_package_exports___Im_svelte_svelte: string;
	export const npm_package_exports___Ma_svelte_svelte: string;
	export const npm_package_exports___Pf_svelte_svelte: string;
	export const npm_package_exports___PkJk_svelte_svelte: string;
	export const npm_package_exports___RuUd_svelte_types: string;
	export const npm_package_exports___Sy_svelte_types: string;
	export const npm_package_exports___Tz_svelte_svelte: string;
	export const npm_package_exports___UsTn_svelte_svelte: string;
	export const npm_package_exports___Az_svelte_types: string;
	export const npm_package_exports___Cl_svelte_svelte: string;
	export const npm_package_exports___Fo_svelte_types: string;
	export const npm_package_exports___Mf_svelte_svelte: string;
	export const npm_package_exports___Pa_svelte_svelte: string;
	export const npm_package_exports___Rs_svelte_types: string;
	export const npm_package_exports___Sd_svelte_types: string;
	export const LESS: string;
	export const LOGNAME: string;
	export const STARSHIP_SESSION_KEY: string;
	export const npm_package_scripts_format: string;
	export const npm_package_exports___Aq_svelte_types: string;
	export const npm_package_exports___Bh_svelte_types: string;
	export const npm_package_exports___CaQc_svelte_svelte: string;
	export const npm_package_exports___Ci_svelte_svelte: string;
	export const npm_package_exports___Easter_island_svelte_svelte: string;
	export const npm_package_exports___EtOr_svelte_svelte: string;
	export const npm_package_exports___Io_svelte_svelte: string;
	export const npm_package_exports___Mc_svelte_svelte: string;
	export const npm_package_exports___Nz_svelte_svelte: string;
	export const npm_package_exports___RuTa_svelte_types: string;
	export const npm_package_exports___So_svelte_types: string;
	export const npm_package_exports___Torres_strait_islands_svelte_types: string;
	export const npm_package_peerDependencies_svelte: string;
	export const npm_package_devDependencies__repo_ui: string;
	export const npm_package_exports___At_svelte_types: string;
	export const npm_package_exports___At_svelte_svelte: string;
	export const npm_package_exports___Bm_svelte_types: string;
	export const npm_package_exports___Bm_svelte_svelte: string;
	export const npm_package_exports___Eh_svelte_types: string;
	export const npm_package_exports___Eh_svelte_svelte: string;
	export const npm_package_exports___Lc_svelte_types: string;
	export const npm_package_exports___Lc_svelte_svelte: string;
	export const npm_lifecycle_script: string;
	export const LC_CTYPE: string;
	export const VSCODE_GIT_IPC_HANDLE: string;
	export const npm_package_author_email: string;
	export const npm_package_scripts_lib_helpers: string;
	export const npm_package_exports___Bz_svelte_types: string;
	export const npm_package_exports___Earth_svelte_svelte: string;
	export const npm_package_exports___Lt_svelte_types: string;
	export const npm_package_exports___Lv_svelte_svelte: string;
	export const npm_package_exports___ShTa_svelte_types: string;
	export const npm_package_exports___Soviet_union_svelte_svelte: string;
	export const SSH_SOCKET_DIR: string;
	export const npm_package_scripts_package: string;
	export const npm_package_scripts_gen_docs: string;
	export const npm_package_exports___Af_svelte_types: string;
	export const npm_package_exports___EsCt_svelte_types: string;
	export const npm_package_exports___Gd_svelte_svelte: string;
	export const npm_package_exports___Kh_svelte_svelte: string;
	export const npm_package_exports___Mz_svelte_svelte: string;
	export const npm_package_exports___Nc_svelte_svelte: string;
	export const npm_package_exports___Ro_svelte_types: string;
	export const npm_package_exports___Sx_svelte_types: string;
	export const npm_package_exports___Vc_svelte_types: string;
	export const npm_package_exports___Zw_svelte_types: string;
	export const NVM_BIN: string;
	export const npm_package_exports___Cc_svelte_types: string;
	export const npm_package_exports___Cm_svelte_svelte: string;
	export const npm_package_exports___Gw_svelte_types: string;
	export const npm_package_exports___Gy_svelte_svelte: string;
	export const npm_package_exports___Ie_svelte_types: string;
	export const npm_package_exports___Mg_svelte_svelte: string;
	export const npm_package_exports___Np_svelte_types: string;
	export const npm_package_exports___Pn_svelte_types: string;
	export const npm_package_exports___Tr_svelte_types: string;
	export const npm_package_exports___UsCa_svelte_svelte: string;
	export const npm_package_exports___UsCo_svelte_types: string;
	export const npm_package_scripts_copy_package: string;
	export const npm_package_exports___BqSa_svelte_types: string;
	export const npm_package_exports___Cn_svelte_svelte: string;
	export const npm_package_exports___IdJb_svelte_types: string;
	export const npm_package_exports___Md_svelte_svelte: string;
	export const npm_package_exports___Mt_svelte_types: string;
	export const npm_package_exports___Ps_svelte_types: string;
	export const npm_package_exports___RuCe_svelte_types: string;
	export const npm_package_exports___RuCu_svelte_svelte: string;
	export const npm_package_exports___To_svelte_types: string;
	export const npm_config_user_agent: string;
	export const GIT_ASKPASS: string;
	export const VSCODE_GIT_ASKPASS_NODE: string;
	export const npm_package_devDependencies__playwright_test: string;
	export const npm_package_exports___AuNsw_svelte_types: string;
	export const npm_package_exports___Bf_svelte_types: string;
	export const npm_package_exports___Cc_svelte_svelte: string;
	export const npm_package_exports___Ec_svelte_types: string;
	export const npm_package_exports___Fj_svelte_types: string;
	export const npm_package_exports___Gw_svelte_svelte: string;
	export const npm_package_exports___Ie_svelte_svelte: string;
	export const npm_package_exports___Maori_svelte_types: string;
	export const npm_package_exports___Nato_svelte_types: string;
	export const npm_package_exports___Np_svelte_svelte: string;
	export const npm_package_exports___Pn_svelte_svelte: string;
	export const npm_package_exports___Sa_svelte_types: string;
	export const npm_package_exports___Tr_svelte_svelte: string;
	export const npm_package_exports___Us_svelte_types: string;
	export const npm_package_exports___UsCo_svelte_svelte: string;
	export const WARP_COMBINED_PROMPT_COMMAND_GRID: string;
	export const npm_package_scripts_package_publish: string;
	export const npm_package_exports___Ar_svelte_types: string;
	export const npm_package_exports___Bs_svelte_svelte: string;
	export const npm_package_exports___De_svelte_svelte: string;
	export const npm_package_exports___EcW_svelte_types: string;
	export const npm_package_exports___EsVariant_svelte_types: string;
	export const npm_package_exports___RuDpr_svelte_svelte: string;
	export const npm_package_exports___RuKo_svelte_types: string;
	export const npm_package_exports___ShAc_svelte_types: string;
	export const npm_package_exports___ShHl_svelte_types: string;
	export const npm_package_exports___Sl_svelte_types: string;
	export const npm_package_exports___St_svelte_svelte: string;
	export const npm_package_files_0: string;
	export const npm_package_exports___Ai_svelte_types: string;
	export const npm_package_exports___Ca_svelte_svelte: string;
	export const npm_package_exports___Gu_svelte_svelte: string;
	export const npm_package_exports___Hr_svelte_types: string;
	export const npm_package_exports___Kikuyu_svelte_types: string;
	export const npm_package_exports___Kongo_svelte_svelte: string;
	export const npm_package_exports___Ky_svelte_svelte: string;
	export const npm_package_exports___Mk_svelte_svelte: string;
	export const npm_package_exports___Nr_svelte_svelte: string;
	export const npm_package_exports___Pl_svelte_svelte: string;
	export const npm_package_exports___Sami_svelte_types: string;
	export const npm_package_exports___UsMo_svelte_svelte: string;
	export const CONDA_CHANGEPS1: string;
	export const npm_package_exports___Be_svelte_svelte: string;
	export const npm_package_exports___EsCn_svelte_svelte: string;
	export const npm_package_exports___EsMl_svelte_svelte: string;
	export const npm_package_exports___Fi_svelte_svelte: string;
	export const npm_package_exports___Hmong_svelte_types: string;
	export const npm_package_exports___Icon_svelte_svelte: string;
	export const npm_package_exports___Id_svelte_types: string;
	export const npm_package_exports___Jm_svelte_types: string;
	export const npm_package_exports___Kz_svelte_types: string;
	export const npm_package_exports___Lk_svelte_svelte: string;
	export const npm_package_exports___Mh_svelte_types: string;
	export const npm_package_exports___Ru_svelte_svelte: string;
	export const npm_package_exports___Sb_svelte_svelte: string;
	export const npm_package_exports___Wf_svelte_types: string;
	export const npm_package_exports___Zm_svelte_svelte: string;
	export const SECURITYSESSIONID: string;
	export const npm_package_exports___Ai_svelte_svelte: string;
	export const npm_package_exports___Bb_svelte_types: string;
	export const npm_package_exports___Eg_svelte_types: string;
	export const npm_package_exports___Hr_svelte_svelte: string;
	export const npm_package_exports___InMn_svelte_types: string;
	export const npm_package_exports___Kikuyu_svelte_svelte: string;
	export const npm_package_exports___RuBa_svelte_types: string;
	export const npm_package_exports___Sami_svelte_svelte: string;
	export const npm_package_exports___Se_svelte_types: string;
	export const npm_package_exports___Transnistria_svelte_types: string;
	export const npm_package_scripts_check: string;
	export const npm_package_exports___Ch_svelte_svelte: string;
	export const npm_package_exports___EsAr_svelte_svelte: string;
	export const npm_package_exports___GbOrk_svelte_svelte: string;
	export const npm_package_exports___Gd_svelte_types: string;
	export const npm_package_exports___GeAb_svelte_svelte: string;
	export const npm_package_exports___IdJt_svelte_svelte: string;
	export const npm_package_exports___In_svelte_svelte: string;
	export const npm_package_exports___Kh_svelte_types: string;
	export const npm_package_exports___Kp_svelte_svelte: string;
	export const npm_package_exports___Mz_svelte_types: string;
	export const npm_package_exports___Nc_svelte_types: string;
	export const npm_package_exports___Pe_svelte_svelte: string;
	export const npm_package_exports___UsHi_svelte_svelte: string;
	export const COLORTERM: string;
	export const npm_package_scripts_test_unit: string;
	export const npm_package_exports___Ae_svelte_types: string;
	export const npm_package_exports___ChGr_svelte_types: string;
	export const npm_package_exports___Dj_svelte_types: string;
	export const npm_package_exports___Fr20r_svelte_types: string;
	export const npm_package_exports___Gq_svelte_svelte: string;
	export const npm_package_exports___Kanuri_svelte_svelte: string;
	export const npm_package_exports___Lr_svelte_types: string;
	export const npm_package_exports___Mo_svelte_svelte: string;
	export const npm_package_exports___Ph_svelte_svelte: string;
	export const npm_package_exports___Tt_svelte_svelte: string;
	export const npm_package_exports___United_nations_svelte_svelte: string;
	export const npm_package_exports___Wiphala_svelte_types: string;
	export const npm_node_execpath: string;
	export const NODE_ENV: string;
}

/**
 * Similar to [`$env/static/private`](https://kit.svelte.dev/docs/modules#$env-static-private), except that it only includes environment variables that begin with [`config.kit.env.publicPrefix`](https://kit.svelte.dev/docs/configuration#env) (which defaults to `PUBLIC_`), and can therefore safely be exposed to client-side code.
 * 
 * Values are replaced statically at build time.
 * 
 * ```ts
 * import { PUBLIC_BASE_URL } from '$env/static/public';
 * ```
 */
declare module '$env/static/public' {
	
}

/**
 * This module provides access to runtime environment variables, as defined by the platform you're running on. For example if you're using [`adapter-node`](https://github.com/sveltejs/kit/tree/main/packages/adapter-node) (or running [`vite preview`](https://kit.svelte.dev/docs/cli)), this is equivalent to `process.env`. This module only includes variables that _do not_ begin with [`config.kit.env.publicPrefix`](https://kit.svelte.dev/docs/configuration#env) _and do_ start with [`config.kit.env.privatePrefix`](https://kit.svelte.dev/docs/configuration#env) (if configured).
 * 
 * This module cannot be imported into client-side code.
 * 
 * Dynamic environment variables cannot be used during prerendering.
 * 
 * ```ts
 * import { env } from '$env/dynamic/private';
 * console.log(env.DEPLOYMENT_SPECIFIC_VARIABLE);
 * ```
 * 
 * > In `dev`, `$env/dynamic` always includes environment variables from `.env`. In `prod`, this behavior will depend on your adapter.
 */
declare module '$env/dynamic/private' {
	export const env: {
		AUTOJUMP_ERROR_PATH: string;
		NVM_INC: string;
		npm_package_exports___Et_svelte_types: string;
		npm_package_exports___Et_svelte_svelte: string;
		npm_package_exports___FrBre_svelte_types: string;
		npm_package_exports___FrBre_svelte_svelte: string;
		npm_package_exports___Sv_svelte_types: string;
		npm_package_exports___Sv_svelte_svelte: string;
		npm_package_exports___UsAl_svelte_types: string;
		npm_package_exports___UsAl_svelte_svelte: string;
		STARSHIP_SHELL: string;
		npm_package_devDependencies_prettier: string;
		npm_package_exports___Au_svelte_svelte: string;
		npm_package_exports___Bl_svelte_svelte: string;
		npm_package_exports___Cy_svelte_types: string;
		npm_package_exports___Dz_svelte_svelte: string;
		npm_package_exports___Gm_svelte_types: string;
		npm_package_exports___Hn_svelte_svelte: string;
		npm_package_exports___Lb_svelte_svelte: string;
		npm_package_exports___Malayali_svelte_types: string;
		npm_package_exports___Ms_svelte_types: string;
		npm_package_exports___Olympics_svelte_types: string;
		npm_package_exports___PkSd_svelte_svelte: string;
		npm_package_exports___Pt_svelte_types: string;
		npm_package_exports___Pt20_svelte_svelte: string;
		npm_package_exports___Sk_svelte_svelte: string;
		npm_package_exports___Th_svelte_types: string;
		npm_package_exports___Uy_svelte_svelte: string;
		npm_package_exports___Ar_svelte_svelte: string;
		npm_package_exports___Bs_svelte_types: string;
		npm_package_exports___De_svelte_types: string;
		npm_package_exports___EcW_svelte_svelte: string;
		npm_package_exports___EsVariant_svelte_svelte: string;
		npm_package_exports___RuDpr_svelte_types: string;
		npm_package_exports___RuKo_svelte_svelte: string;
		npm_package_exports___ShAc_svelte_svelte: string;
		npm_package_exports___ShHl_svelte_svelte: string;
		npm_package_exports___Sl_svelte_svelte: string;
		npm_package_exports___St_svelte_types: string;
		TERM_PROGRAM: string;
		npm_package_devDependencies_eslint_plugin_svelte: string;
		npm_package_exports___Aw_svelte_svelte: string;
		npm_package_exports___Bn_svelte_svelte: string;
		npm_package_exports___Earth_svelte_types: string;
		npm_package_exports___EsCe_svelte_svelte: string;
		npm_package_exports___Lv_svelte_types: string;
		npm_package_exports___Si_svelte_svelte: string;
		npm_package_exports___Soviet_union_svelte_types: string;
		npm_package_exports___UsGa_svelte_svelte: string;
		NODE: string;
		npm_package_exports___Ad_svelte_types: string;
		npm_package_exports___Ad_svelte_svelte: string;
		npm_package_exports___Dk_svelte_types: string;
		npm_package_exports___Dk_svelte_svelte: string;
		npm_package_exports___European_union_svelte_types: string;
		npm_package_exports___European_union_svelte_svelte: string;
		npm_package_exports___Ls_svelte_types: string;
		npm_package_exports___Ls_svelte_svelte: string;
		npm_package_exports___Sz_svelte_types: string;
		npm_package_exports___Sz_svelte_svelte: string;
		npm_package_exports___UsRi_svelte_types: string;
		npm_package_exports___UsRi_svelte_svelte: string;
		npm_package_exports___Va_svelte_types: string;
		npm_package_exports___Va_svelte_svelte: string;
		AUTOJUMP_SOURCED: string;
		INIT_CWD: string;
		NVM_CD_FLAGS: string;
		TURBO_INVOCATION_DIR: string;
		npm_package_homepage: string;
		npm_package_devDependencies_prettier_plugin_svelte: string;
		npm_package_devDependencies_typescript: string;
		npm_package_exports___Afar_svelte_types: string;
		npm_package_exports___AqTrue_south_svelte_types: string;
		npm_package_exports___Gi_svelte_types: string;
		npm_package_exports___Jp_svelte_svelte: string;
		npm_package_exports___Ke_svelte_types: string;
		npm_package_exports___Kg_svelte_svelte: string;
		npm_package_exports___Mu_svelte_svelte: string;
		npm_package_exports___Mw_svelte_types: string;
		npm_package_exports___Nl_svelte_svelte: string;
		npm_package_exports___Pr_svelte_svelte: string;
		npm_package_exports___Qa_svelte_svelte: string;
		npm_package_exports___Tl_svelte_types: string;
		npm_package_exports___Tn_svelte_svelte: string;
		npm_package_exports___UsMs_svelte_types: string;
		npm_package_exports___UsTx_svelte_types: string;
		SHELL: string;
		TERM: string;
		WARP_HONOR_PS1: string;
		npm_package_devDependencies_vite: string;
		npm_package_exports___CaBc_svelte_svelte: string;
		npm_package_exports___Cx_svelte_types: string;
		npm_package_exports___EsIb_svelte_svelte: string;
		npm_package_exports___Gl_svelte_types: string;
		npm_package_exports___Gt_svelte_svelte: string;
		npm_package_exports___Jo_svelte_svelte: string;
		npm_package_exports___Mr_svelte_types: string;
		npm_package_exports___Northern_cyprus_svelte_svelte: string;
		npm_package_exports___Pm_svelte_svelte: string;
		npm_package_devDependencies_svelte_lib_helpers: string;
		npm_package_exports___AfEmirate_svelte_svelte: string;
		npm_package_exports___As_svelte_svelte: string;
		npm_package_exports___AuAboriginal_svelte_types: string;
		npm_package_exports___Bd_svelte_types: string;
		npm_package_exports___Bj_svelte_svelte: string;
		npm_package_exports___GbNir_svelte_svelte: string;
		npm_package_exports___InGj_svelte_types: string;
		npm_package_exports___InOr_svelte_types: string;
		npm_package_exports___NlFr_svelte_types: string;
		npm_package_exports___Sc_svelte_types: string;
		npm_package_exports___Sm_svelte_svelte: string;
		npm_package_exports___Xx_svelte_svelte: string;
		npm_package_exports___Ye_svelte_types: string;
		TMPDIR: string;
		npm_package_exports___Bi_svelte_svelte: string;
		npm_package_exports___Cn_svelte_types: string;
		npm_package_exports___Hk_svelte_svelte: string;
		npm_package_exports___Md_svelte_types: string;
		npm_package_exports___RuCu_svelte_types: string;
		npm_package_exports___Sn_svelte_svelte: string;
		npm_package_exports___Vu_svelte_svelte: string;
		npm_package_exports___Za_svelte_svelte: string;
		npm_package_scripts_lint: string;
		npm_package_exports___Ao_svelte_types: string;
		npm_package_exports___AuAboriginal_svelte_svelte: string;
		npm_package_exports___AuAct_svelte_types: string;
		npm_package_exports___Bd_svelte_svelte: string;
		npm_package_exports___Es_svelte_types: string;
		npm_package_exports___Hausa_svelte_types: string;
		npm_package_exports___Ht_svelte_types: string;
		npm_package_exports___InGj_svelte_svelte: string;
		npm_package_exports___InMz_svelte_types: string;
		npm_package_exports___InOr_svelte_svelte: string;
		npm_package_exports___NlFr_svelte_svelte: string;
		npm_package_exports___Om_svelte_types: string;
		npm_package_exports___Otomi_svelte_types: string;
		npm_package_exports___Sc_svelte_svelte: string;
		npm_package_exports___South_ossetia_svelte_types: string;
		npm_package_exports___UsAk_svelte_types: string;
		npm_package_exports___Ye_svelte_svelte: string;
		TERM_PROGRAM_VERSION: string;
		npm_package_exports___Dm_svelte_types: string;
		npm_package_exports___FrCp_svelte_svelte: string;
		npm_package_exports___GbSct_svelte_types: string;
		npm_package_exports___Ir_svelte_svelte: string;
		npm_package_exports___Lu_svelte_types: string;
		npm_package_exports___Ng_svelte_svelte: string;
		npm_package_exports___Pt30_svelte_svelte: string;
		npm_package_exports___Py_svelte_svelte: string;
		npm_package_exports___RuLpr_svelte_types: string;
		npm_package_exports___UsNc_svelte_svelte: string;
		npm_package_exports___Vg_svelte_types: string;
		npm_package_scripts_dev: string;
		npm_package_devDependencies_postcss_load_config: string;
		npm_package_exports___AuNsw_svelte_svelte: string;
		npm_package_exports___AuWa_svelte_types: string;
		npm_package_exports___Bf_svelte_svelte: string;
		npm_package_exports___Cw_svelte_types: string;
		npm_package_exports___Ec_svelte_svelte: string;
		npm_package_exports___Fj_svelte_svelte: string;
		npm_package_exports___Iq_svelte_types: string;
		npm_package_exports___Maori_svelte_svelte: string;
		npm_package_exports___Nato_svelte_svelte: string;
		npm_package_exports___Quechua_svelte_types: string;
		npm_package_exports___Sa_svelte_svelte: string;
		npm_package_exports___Somaliland_svelte_types: string;
		npm_package_exports___Tf_svelte_types: string;
		npm_package_exports___Us_svelte_svelte: string;
		npm_package_exports___Ws_svelte_types: string;
		MallocNanoZone: string;
		ORIGINAL_XDG_CURRENT_DESKTOP: string;
		ZDOTDIR: string;
		npm_package_scripts_prepublishOnly: string;
		npm_package_exports___Al_svelte_svelte: string;
		npm_package_exports___Be_svelte_types: string;
		npm_package_exports___EsCn_svelte_types: string;
		npm_package_exports___EsMl_svelte_types: string;
		npm_package_exports___Fi_svelte_types: string;
		npm_package_exports___Icon_svelte_types: string;
		npm_package_exports___Lk_svelte_types: string;
		npm_package_exports___Re_svelte_svelte: string;
		npm_package_exports___Ru_svelte_types: string;
		npm_package_exports___Sb_svelte_types: string;
		npm_package_exports___Sr_svelte_svelte: string;
		npm_package_exports___Vi_svelte_svelte: string;
		npm_package_exports___Yt_svelte_svelte: string;
		npm_package_exports___Zm_svelte_types: string;
		npm_package_exports___AuTas_svelte_types: string;
		npm_package_exports___AuWa_svelte_svelte: string;
		npm_package_exports___Br_svelte_types: string;
		npm_package_exports___Cw_svelte_svelte: string;
		npm_package_exports___East_african_federation_svelte_types: string;
		npm_package_exports___Iq_svelte_svelte: string;
		npm_package_exports___Quechua_svelte_svelte: string;
		npm_package_exports___Somaliland_svelte_svelte: string;
		npm_package_exports___Tf_svelte_svelte: string;
		npm_package_exports___Tibet_svelte_types: string;
		npm_package_exports___Ug_svelte_types: string;
		npm_package_exports___Vn_svelte_types: string;
		npm_package_exports___Ws_svelte_svelte: string;
		npm_package_devDependencies__sveltejs_kit: string;
		npm_package_devDependencies_svelte_preprocess: string;
		npm_package_exports___svelte: string;
		npm_package_exports___Bo_svelte_svelte: string;
		npm_package_exports___CaBc_svelte_types: string;
		npm_package_exports___EsIb_svelte_types: string;
		npm_package_exports___Gt_svelte_types: string;
		npm_package_exports___Jo_svelte_types: string;
		npm_package_exports___La_svelte_svelte: string;
		npm_package_exports___Northern_cyprus_svelte_types: string;
		npm_package_exports___Pm_svelte_types: string;
		npm_package_exports___UsAr_svelte_svelte: string;
		npm_package_exports___Uz_svelte_svelte: string;
		npm_config_registry: string;
		ZSH: string;
		npm_package_devDependencies__floating_ui_dom: string;
		npm_package_repository_url: string;
		npm_package_exports___AuSa_svelte_types: string;
		npm_package_exports___AuVic_svelte_types: string;
		npm_package_exports___Bb_svelte_svelte: string;
		npm_package_exports___Eg_svelte_svelte: string;
		npm_package_exports___InMn_svelte_svelte: string;
		npm_package_exports___InTg_svelte_types: string;
		npm_package_exports___Mq_svelte_types: string;
		npm_package_exports___RuBa_svelte_svelte: string;
		npm_package_exports___Se_svelte_svelte: string;
		npm_package_exports___Tj_svelte_types: string;
		npm_package_exports___Transnistria_svelte_svelte: string;
		npm_package_exports___Cv_svelte_types: string;
		npm_package_exports___Cv_svelte_svelte: string;
		npm_package_exports___Gb_svelte_types: string;
		npm_package_exports___Gb_svelte_svelte: string;
		npm_package_exports___GbWls_svelte_types: string;
		npm_package_exports___GbWls_svelte_svelte: string;
		npm_package_exports___Kn_svelte_types: string;
		npm_package_exports___Kn_svelte_svelte: string;
		npm_package_exports___MqOld_svelte_types: string;
		npm_package_exports___MqOld_svelte_svelte: string;
		npm_package_exports___Ne_svelte_types: string;
		npm_package_exports___Ne_svelte_svelte: string;
		npm_package_exports___Tg_svelte_types: string;
		npm_package_exports___Tg_svelte_svelte: string;
		npm_package_exports___UsDc_svelte_types: string;
		npm_package_exports___UsDc_svelte_svelte: string;
		NVM_DIR: string;
		USER: string;
		npm_package_description: string;
		npm_package_exports___Ae_svelte_svelte: string;
		npm_package_exports___CaQc_svelte_types: string;
		npm_package_exports___ChGr_svelte_svelte: string;
		npm_package_exports___Ci_svelte_types: string;
		npm_package_exports___Dj_svelte_svelte: string;
		npm_package_exports___Easter_island_svelte_types: string;
		npm_package_exports___EtOr_svelte_types: string;
		npm_package_exports___Fr20r_svelte_svelte: string;
		npm_package_exports___Io_svelte_types: string;
		npm_package_exports___Lr_svelte_svelte: string;
		npm_package_exports___Mc_svelte_types: string;
		npm_package_exports___Nz_svelte_types: string;
		npm_package_exports___Wiphala_svelte_svelte: string;
		LS_COLORS: string;
		npm_package_license: string;
		npm_package_scripts_check_watch: string;
		npm_package_exports___Dm_svelte_svelte: string;
		npm_package_exports___FrCp_svelte_types: string;
		npm_package_exports___GbSct_svelte_svelte: string;
		npm_package_exports___Ir_svelte_types: string;
		npm_package_exports___Lu_svelte_svelte: string;
		npm_package_exports___Ng_svelte_types: string;
		npm_package_exports___Pt30_svelte_types: string;
		npm_package_exports___Py_svelte_types: string;
		npm_package_exports___RuLpr_svelte_svelte: string;
		npm_package_exports___UsNc_svelte_types: string;
		npm_package_exports___Vg_svelte_svelte: string;
		COMMAND_MODE: string;
		npm_package_devDependencies_mdsvex: string;
		npm_package_exports___Ag_svelte_svelte: string;
		npm_package_exports___AuNt_svelte_svelte: string;
		npm_package_exports___EsGa_svelte_svelte: string;
		npm_package_exports___Fr_svelte_svelte: string;
		npm_package_exports___Jp_svelte_types: string;
		npm_package_exports___Kg_svelte_types: string;
		npm_package_exports___Mu_svelte_types: string;
		npm_package_exports___Nl_svelte_types: string;
		npm_package_exports___Pr_svelte_types: string;
		npm_package_exports___Qa_svelte_types: string;
		npm_package_exports___RuUd_svelte_svelte: string;
		npm_package_exports___Sy_svelte_svelte: string;
		npm_package_exports___Tn_svelte_types: string;
		PNPM_SCRIPT_SRC_DIR: string;
		npm_package_exports___BqSe_svelte_types: string;
		npm_package_exports___BqSe_svelte_svelte: string;
		npm_package_exports___Cz_svelte_types: string;
		npm_package_exports___Cz_svelte_svelte: string;
		npm_package_exports___GbEng_svelte_types: string;
		npm_package_exports___GbEng_svelte_svelte: string;
		npm_package_exports___Gn_svelte_types: string;
		npm_package_exports___Gn_svelte_svelte: string;
		npm_package_exports___Mp_svelte_types: string;
		npm_package_exports___Mp_svelte_svelte: string;
		npm_package_exports___Ni_svelte_types: string;
		npm_package_exports___Ni_svelte_svelte: string;
		npm_package_exports___Occitania_svelte_types: string;
		npm_package_exports___Occitania_svelte_svelte: string;
		npm_package_exports___Pw_svelte_types: string;
		npm_package_exports___Pw_svelte_svelte: string;
		npm_package_exports___Tk_svelte_types: string;
		npm_package_exports___Tk_svelte_svelte: string;
		npm_package_exports___UsNm_svelte_types: string;
		npm_package_exports___UsNm_svelte_svelte: string;
		npm_package_exports___Cm_svelte_types: string;
		npm_package_exports___Co_svelte_svelte: string;
		npm_package_exports___EsPv_svelte_svelte: string;
		npm_package_exports___Gy_svelte_types: string;
		npm_package_exports___Kw_svelte_svelte: string;
		npm_package_exports___Me_svelte_svelte: string;
		npm_package_exports___Mg_svelte_types: string;
		npm_package_exports___RuDa_svelte_svelte: string;
		npm_package_exports___UsCa_svelte_types: string;
		SSH_AUTH_SOCK: string;
		npm_package_exports___Bg_svelte_svelte: string;
		npm_package_exports___Ch_svelte_types: string;
		npm_package_exports___EsAr_svelte_types: string;
		npm_package_exports___Fk_svelte_svelte: string;
		npm_package_exports___GbOrk_svelte_types: string;
		npm_package_exports___GeAb_svelte_types: string;
		npm_package_exports___IdJt_svelte_types: string;
		npm_package_exports___In_svelte_types: string;
		npm_package_exports___Kp_svelte_types: string;
		npm_package_exports___Li_svelte_svelte: string;
		npm_package_exports___Pe_svelte_types: string;
		npm_package_exports___Rw_svelte_svelte: string;
		npm_package_exports___UsAz_svelte_svelte: string;
		npm_package_exports___UsHi_svelte_types: string;
		WARP_IS_LOCAL_SHELL_SESSION: string;
		__CF_USER_TEXT_ENCODING: string;
		npm_package_devDependencies_eslint: string;
		npm_package_devDependencies_postcss: string;
		npm_package_exports___Am_svelte_types: string;
		npm_package_exports___Bt_svelte_types: string;
		npm_package_exports___Bz_svelte_svelte: string;
		npm_package_exports___Lt_svelte_svelte: string;
		npm_package_exports___ShTa_svelte_svelte: string;
		npm_package_exports___Ss_svelte_types: string;
		npm_package_exports___Ua_svelte_types: string;
		npm_package_exports___UsFl_svelte_types: string;
		npm_package_exports___Yu_svelte_types: string;
		npm_package_devDependencies__typescript_eslint_eslint_plugin: string;
		npm_package_devDependencies_tslib: string;
		npm_package_exports___Bi_svelte_types: string;
		npm_package_exports___By_svelte_svelte: string;
		npm_package_exports___Do_svelte_svelte: string;
		npm_package_exports___Hk_svelte_types: string;
		npm_package_exports___Sn_svelte_types: string;
		npm_package_exports___Ve_svelte_svelte: string;
		npm_package_exports___Vu_svelte_types: string;
		npm_package_exports___Xk_svelte_svelte: string;
		npm_package_exports___Za_svelte_types: string;
		npm_execpath: string;
		PAGER: string;
		WARP_USE_SSH_WRAPPER: string;
		npm_package_devDependencies_svelte: string;
		npm_package_devDependencies_svelte_meta_tags: string;
		npm_package_exports___Am_svelte_svelte: string;
		npm_package_exports___Bt_svelte_svelte: string;
		npm_package_exports___Cq_svelte_types: string;
		npm_package_exports___Ge_svelte_types: string;
		npm_package_exports___Ki_svelte_types: string;
		npm_package_exports___Ss_svelte_svelte: string;
		npm_package_exports___Ua_svelte_svelte: string;
		npm_package_exports___UsFl_svelte_svelte: string;
		npm_package_exports___Yu_svelte_svelte: string;
		npm_package_author_name: string;
		npm_package_exports___Cd_svelte_svelte: string;
		npm_package_exports___CnXj_svelte_types: string;
		npm_package_exports___Gh_svelte_types: string;
		npm_package_exports___Gp_svelte_svelte: string;
		npm_package_exports___InAs_svelte_types: string;
		npm_package_exports___InKa_svelte_types: string;
		npm_package_exports___IqKr_svelte_types: string;
		npm_package_exports___Mn_svelte_svelte: string;
		npm_package_exports___Mv_svelte_types: string;
		npm_package_exports___No_svelte_types: string;
		npm_package_exports___Tm_svelte_types: string;
		npm_package_exports___UsIn_svelte_types: string;
		LSCOLORS: string;
		npm_package_exports___Ao_svelte_svelte: string;
		npm_package_exports___AuAct_svelte_svelte: string;
		npm_package_exports___Cg_svelte_types: string;
		npm_package_exports___Es_svelte_svelte: string;
		npm_package_exports___Gs_svelte_types: string;
		npm_package_exports___Hausa_svelte_svelte: string;
		npm_package_exports___Ht_svelte_svelte: string;
		npm_package_exports___InMz_svelte_svelte: string;
		npm_package_exports___Mm_svelte_types: string;
		npm_package_exports___Om_svelte_svelte: string;
		npm_package_exports___Otomi_svelte_svelte: string;
		npm_package_exports___South_ossetia_svelte_svelte: string;
		npm_package_exports___Tv_svelte_types: string;
		npm_package_exports___UsAk_svelte_svelte: string;
		npm_config_frozen_lockfile: string;
		npm_package_devDependencies__typescript_eslint_parser: string;
		npm_package_exports___Al_svelte_types: string;
		npm_package_exports___Cr_svelte_svelte: string;
		npm_package_exports___Ewe_svelte_svelte: string;
		npm_package_exports___Gf_svelte_svelte: string;
		npm_package_exports___Guarani_svelte_svelte: string;
		npm_package_exports___InTn_svelte_svelte: string;
		npm_package_exports___It_svelte_svelte: string;
		npm_package_exports___Mx_svelte_svelte: string;
		npm_package_exports___Na_svelte_svelte: string;
		npm_package_exports___Re_svelte_types: string;
		npm_package_exports___Sr_svelte_types: string;
		npm_package_exports___Tc_svelte_svelte: string;
		npm_package_exports___Vi_svelte_types: string;
		npm_package_exports___Yt_svelte_types: string;
		PATH: string;
		npm_package_exports___Cg_svelte_svelte: string;
		npm_package_exports___Cu_svelte_types: string;
		npm_package_exports___Ga_svelte_types: string;
		npm_package_exports___Gs_svelte_svelte: string;
		npm_package_exports___Is_svelte_types: string;
		npm_package_exports___Km_svelte_types: string;
		npm_package_exports___Mm_svelte_svelte: string;
		npm_package_exports___Nf_svelte_types: string;
		npm_package_exports___Td_svelte_types: string;
		npm_package_exports___Tv_svelte_svelte: string;
		npm_package_exports___Af_svelte_svelte: string;
		npm_package_exports___Bg_svelte_types: string;
		npm_package_exports___EsCt_svelte_svelte: string;
		npm_package_exports___Fk_svelte_types: string;
		npm_package_exports___Li_svelte_types: string;
		npm_package_exports___Ro_svelte_svelte: string;
		npm_package_exports___Rw_svelte_types: string;
		npm_package_exports___Sx_svelte_svelte: string;
		npm_package_exports___UsAz_svelte_types: string;
		npm_package_exports___Vc_svelte_svelte: string;
		npm_package_exports___Zw_svelte_svelte: string;
		LaunchInstanceID: string;
		npm_package_exports___AuTas_svelte_svelte: string;
		npm_package_exports___Br_svelte_svelte: string;
		npm_package_exports___Ck_svelte_types: string;
		npm_package_exports___East_african_federation_svelte_svelte: string;
		npm_package_exports___Im_svelte_types: string;
		npm_package_exports___Ma_svelte_types: string;
		npm_package_exports___Pf_svelte_types: string;
		npm_package_exports___PkJk_svelte_types: string;
		npm_package_exports___Tibet_svelte_svelte: string;
		npm_package_exports___Tz_svelte_types: string;
		npm_package_exports___Ug_svelte_svelte: string;
		npm_package_exports___UsTn_svelte_types: string;
		npm_package_exports___Vn_svelte_svelte: string;
		npm_config_engine_strict: string;
		USER_ZDOTDIR: string;
		__CFBundleIdentifier: string;
		npm_package_bugs: string;
		npm_package_keywords_4: string;
		npm_package_exports___Cf_svelte_types: string;
		npm_package_exports___Cf_svelte_svelte: string;
		npm_package_exports___Gr_svelte_types: string;
		npm_package_exports___Gr_svelte_svelte: string;
		npm_package_exports___Ml_svelte_types: string;
		npm_package_exports___Ml_svelte_svelte: string;
		npm_package_exports___Nu_svelte_types: string;
		npm_package_exports___Nu_svelte_svelte: string;
		npm_package_exports___Pk_svelte_types: string;
		npm_package_exports___Pk_svelte_svelte: string;
		npm_package_exports___Tw_svelte_types: string;
		npm_package_exports___Tw_svelte_svelte: string;
		PWD: string;
		npm_package_devDependencies_tailwindcss: string;
		npm_package_exports___AuSa_svelte_svelte: string;
		npm_package_exports___AuVic_svelte_svelte: string;
		npm_package_exports___Aw_svelte_types: string;
		npm_package_exports___Bn_svelte_types: string;
		npm_package_exports___EsCe_svelte_types: string;
		npm_package_exports___InTg_svelte_svelte: string;
		npm_package_exports___Mq_svelte_svelte: string;
		npm_package_exports___Si_svelte_types: string;
		npm_package_exports___Tj_svelte_svelte: string;
		npm_package_exports___UsGa_svelte_types: string;
		npm_command: string;
		npm_package_author_url: string;
		npm_package_scripts_preview: string;
		npm_package_devDependencies__sveltejs_package: string;
		npm_package_devDependencies_publint: string;
		npm_package_exports___Cd_svelte_types: string;
		npm_package_exports___CnXj_svelte_svelte: string;
		npm_package_exports___Gh_svelte_svelte: string;
		npm_package_exports___Gp_svelte_types: string;
		npm_package_exports___InAs_svelte_svelte: string;
		npm_package_exports___InKa_svelte_svelte: string;
		npm_package_exports___IqKr_svelte_svelte: string;
		npm_package_exports___Mn_svelte_types: string;
		npm_package_exports___Mv_svelte_svelte: string;
		npm_package_exports___No_svelte_svelte: string;
		npm_package_exports___Tm_svelte_svelte: string;
		npm_package_exports___UsIn_svelte_svelte: string;
		npm_package_exports___Co_svelte_types: string;
		npm_package_exports___Cy_svelte_svelte: string;
		npm_package_exports___EsPv_svelte_types: string;
		npm_package_exports___Gm_svelte_svelte: string;
		npm_package_exports___Kw_svelte_types: string;
		npm_package_exports___Malayali_svelte_svelte: string;
		npm_package_exports___Me_svelte_types: string;
		npm_package_exports___Ms_svelte_svelte: string;
		npm_package_exports___Olympics_svelte_svelte: string;
		npm_package_exports___Pt_svelte_svelte: string;
		npm_package_exports___RuDa_svelte_types: string;
		npm_package_exports___Th_svelte_svelte: string;
		npm_lifecycle_event: string;
		LANG: string;
		npm_package_name: string;
		npm_package_devDependencies__sveltejs_vite_plugin_svelte: string;
		npm_package_svelte: string;
		npm_package_types: string;
		npm_package_keywords_0: string;
		npm_package_repository_type: string;
		npm_package_exports___GbCon_svelte_types: string;
		npm_package_exports___GbCon_svelte_svelte: string;
		npm_package_exports___Il_svelte_types: string;
		npm_package_exports___Il_svelte_svelte: string;
		npm_package_exports___Je_svelte_types: string;
		npm_package_exports___Je_svelte_svelte: string;
		npm_package_exports___Kr_svelte_types: string;
		npm_package_exports___Kr_svelte_svelte: string;
		npm_package_exports___Mars_svelte_types: string;
		npm_package_exports___Mars_svelte_svelte: string;
		npm_package_exports___Pg_svelte_types: string;
		npm_package_exports___Pg_svelte_svelte: string;
		npm_package_exports___Yorubaland_svelte_types: string;
		npm_package_exports___Yorubaland_svelte_svelte: string;
		npm_package_scripts_test_integration: string;
		npm_package_keywords_1: string;
		npm_package_exports___AfEmirate_svelte_types: string;
		npm_package_exports___Aq_svelte_svelte: string;
		npm_package_exports___As_svelte_types: string;
		npm_package_exports___Bh_svelte_svelte: string;
		npm_package_exports___Bj_svelte_types: string;
		npm_package_exports___GbNir_svelte_types: string;
		npm_package_exports___RuTa_svelte_svelte: string;
		npm_package_exports___Sm_svelte_types: string;
		npm_package_exports___So_svelte_svelte: string;
		npm_package_exports___Torres_strait_islands_svelte_svelte: string;
		npm_package_exports___Xx_svelte_types: string;
		NODE_PATH: string;
		npm_package_scripts_build: string;
		npm_package_devDependencies_svelte_toc: string;
		npm_package_keywords_2: string;
		npm_package_exports___types: string;
		npm_package_exports___An_svelte_svelte: string;
		npm_package_exports___AuQld_svelte_svelte: string;
		npm_package_exports___Bo_svelte_types: string;
		npm_package_exports___Bw_svelte_svelte: string;
		npm_package_exports___Er_svelte_svelte: string;
		npm_package_exports___Hu_svelte_svelte: string;
		npm_package_exports___La_svelte_types: string;
		npm_package_exports___Ly_svelte_svelte: string;
		npm_package_exports___UsAr_svelte_types: string;
		npm_package_exports___Uz_svelte_types: string;
		TURBO_HASH: string;
		VSCODE_GIT_ASKPASS_EXTRA_ARGS: string;
		XPC_FLAGS: string;
		npm_package_devDependencies_vitest: string;
		npm_package_keywords_3: string;
		npm_package_exports___Afar_svelte_svelte: string;
		npm_package_exports___AqTrue_south_svelte_svelte: string;
		npm_package_exports___EtTi_svelte_types: string;
		npm_package_exports___Gg_svelte_types: string;
		npm_package_exports___Gi_svelte_svelte: string;
		npm_package_exports___Ke_svelte_svelte: string;
		npm_package_exports___Mw_svelte_svelte: string;
		npm_package_exports___My_svelte_types: string;
		npm_package_exports___Tl_svelte_svelte: string;
		npm_package_exports___UsMs_svelte_svelte: string;
		npm_package_exports___UsTx_svelte_svelte: string;
		npm_package_scripts_gen_compo_data: string;
		npm_package_devDependencies_flowbite_svelte: string;
		npm_package_exports___BqSa_svelte_svelte: string;
		npm_package_exports___By_svelte_types: string;
		npm_package_exports___Do_svelte_types: string;
		npm_package_exports___IdJb_svelte_svelte: string;
		npm_package_exports___Mt_svelte_svelte: string;
		npm_package_exports___Ps_svelte_svelte: string;
		npm_package_exports___RuCe_svelte_svelte: string;
		npm_package_exports___To_svelte_svelte: string;
		npm_package_exports___Ve_svelte_types: string;
		npm_package_exports___Xk_svelte_types: string;
		npm_package_devDependencies_tailwind_merge: string;
		npm_package_exports___Ca_svelte_types: string;
		npm_package_exports___EtTi_svelte_svelte: string;
		npm_package_exports___Gg_svelte_svelte: string;
		npm_package_exports___Gu_svelte_types: string;
		npm_package_exports___Kongo_svelte_types: string;
		npm_package_exports___Ky_svelte_types: string;
		npm_package_exports___Mk_svelte_types: string;
		npm_package_exports___My_svelte_svelte: string;
		npm_package_exports___Nr_svelte_types: string;
		npm_package_exports___Pl_svelte_types: string;
		npm_package_exports___UsMo_svelte_types: string;
		npm_package_main: string;
		npm_package_devDependencies_eslint_config_prettier: string;
		npm_package_exports___Az_svelte_svelte: string;
		npm_package_exports___Cl_svelte_types: string;
		npm_package_exports___Fo_svelte_svelte: string;
		npm_package_exports___Mf_svelte_types: string;
		npm_package_exports___Pa_svelte_types: string;
		npm_package_exports___Rs_svelte_svelte: string;
		npm_package_exports___Sd_svelte_svelte: string;
		npm_config_node_gyp: string;
		XPC_SERVICE_NAME: string;
		npm_package_version: string;
		npm_package_devDependencies__sveltejs_adapter_auto: string;
		npm_package_exports___BqBo_svelte_types: string;
		npm_package_exports___Cq_svelte_svelte: string;
		npm_package_exports___Ee_svelte_types: string;
		npm_package_exports___Ge_svelte_svelte: string;
		npm_package_exports___Ki_svelte_svelte: string;
		npm_package_exports___Sg_svelte_types: string;
		VSCODE_INJECTION: string;
		npm_package_devDependencies_autoprefixer: string;
		npm_package_devDependencies_svelte_check: string;
		npm_package_exports___Cr_svelte_types: string;
		npm_package_exports___Ewe_svelte_types: string;
		npm_package_exports___Gf_svelte_types: string;
		npm_package_exports___Guarani_svelte_types: string;
		npm_package_exports___Hmong_svelte_svelte: string;
		npm_package_exports___Id_svelte_svelte: string;
		npm_package_exports___InTn_svelte_types: string;
		npm_package_exports___It_svelte_types: string;
		npm_package_exports___Jm_svelte_svelte: string;
		npm_package_exports___Kz_svelte_svelte: string;
		npm_package_exports___Mh_svelte_svelte: string;
		npm_package_exports___Mx_svelte_types: string;
		npm_package_exports___Na_svelte_types: string;
		npm_package_exports___Tc_svelte_types: string;
		npm_package_exports___Wf_svelte_svelte: string;
		HOME: string;
		SHLVL: string;
		npm_package_type: string;
		npm_package_exports___BqBo_svelte_svelte: string;
		npm_package_exports___Ee_svelte_svelte: string;
		npm_package_exports___Gq_svelte_types: string;
		npm_package_exports___Kanuri_svelte_types: string;
		npm_package_exports___Mo_svelte_types: string;
		npm_package_exports___Ph_svelte_types: string;
		npm_package_exports___Sg_svelte_svelte: string;
		npm_package_exports___Tt_svelte_types: string;
		npm_package_exports___United_nations_svelte_types: string;
		VSCODE_GIT_ASKPASS_MAIN: string;
		npm_package_scripts_test: string;
		npm_package_exports___An_svelte_types: string;
		npm_package_exports___AuQld_svelte_types: string;
		npm_package_exports___Bw_svelte_types: string;
		npm_package_exports___Cx_svelte_svelte: string;
		npm_package_exports___Er_svelte_types: string;
		npm_package_exports___Gl_svelte_svelte: string;
		npm_package_exports___Hu_svelte_types: string;
		npm_package_exports___Ly_svelte_types: string;
		npm_package_exports___Mr_svelte_svelte: string;
		npm_package_exports___Au_svelte_types: string;
		npm_package_exports___Bl_svelte_types: string;
		npm_package_exports___Cu_svelte_svelte: string;
		npm_package_exports___Dz_svelte_types: string;
		npm_package_exports___Ga_svelte_svelte: string;
		npm_package_exports___Hn_svelte_types: string;
		npm_package_exports___Is_svelte_svelte: string;
		npm_package_exports___Km_svelte_svelte: string;
		npm_package_exports___Lb_svelte_types: string;
		npm_package_exports___Nf_svelte_svelte: string;
		npm_package_exports___PkSd_svelte_types: string;
		npm_package_exports___Pt20_svelte_types: string;
		npm_package_exports___Sk_svelte_types: string;
		npm_package_exports___Td_svelte_svelte: string;
		npm_package_exports___Uy_svelte_types: string;
		HOMEBREW_PREFIX: string;
		npm_package_scripts_gen_exports: string;
		npm_package_exports___Ax_svelte_types: string;
		npm_package_exports___Ax_svelte_svelte: string;
		npm_package_exports___Ba_svelte_types: string;
		npm_package_exports___Ba_svelte_svelte: string;
		npm_package_exports___Fm_svelte_types: string;
		npm_package_exports___Fm_svelte_svelte: string;
		npm_package_exports___Ag_svelte_types: string;
		npm_package_exports___AuNt_svelte_types: string;
		npm_package_exports___Ck_svelte_svelte: string;
		npm_package_exports___EsGa_svelte_types: string;
		npm_package_exports___Fr_svelte_types: string;
		npm_package_exports___Im_svelte_svelte: string;
		npm_package_exports___Ma_svelte_svelte: string;
		npm_package_exports___Pf_svelte_svelte: string;
		npm_package_exports___PkJk_svelte_svelte: string;
		npm_package_exports___RuUd_svelte_types: string;
		npm_package_exports___Sy_svelte_types: string;
		npm_package_exports___Tz_svelte_svelte: string;
		npm_package_exports___UsTn_svelte_svelte: string;
		npm_package_exports___Az_svelte_types: string;
		npm_package_exports___Cl_svelte_svelte: string;
		npm_package_exports___Fo_svelte_types: string;
		npm_package_exports___Mf_svelte_svelte: string;
		npm_package_exports___Pa_svelte_svelte: string;
		npm_package_exports___Rs_svelte_types: string;
		npm_package_exports___Sd_svelte_types: string;
		LESS: string;
		LOGNAME: string;
		STARSHIP_SESSION_KEY: string;
		npm_package_scripts_format: string;
		npm_package_exports___Aq_svelte_types: string;
		npm_package_exports___Bh_svelte_types: string;
		npm_package_exports___CaQc_svelte_svelte: string;
		npm_package_exports___Ci_svelte_svelte: string;
		npm_package_exports___Easter_island_svelte_svelte: string;
		npm_package_exports___EtOr_svelte_svelte: string;
		npm_package_exports___Io_svelte_svelte: string;
		npm_package_exports___Mc_svelte_svelte: string;
		npm_package_exports___Nz_svelte_svelte: string;
		npm_package_exports___RuTa_svelte_types: string;
		npm_package_exports___So_svelte_types: string;
		npm_package_exports___Torres_strait_islands_svelte_types: string;
		npm_package_peerDependencies_svelte: string;
		npm_package_devDependencies__repo_ui: string;
		npm_package_exports___At_svelte_types: string;
		npm_package_exports___At_svelte_svelte: string;
		npm_package_exports___Bm_svelte_types: string;
		npm_package_exports___Bm_svelte_svelte: string;
		npm_package_exports___Eh_svelte_types: string;
		npm_package_exports___Eh_svelte_svelte: string;
		npm_package_exports___Lc_svelte_types: string;
		npm_package_exports___Lc_svelte_svelte: string;
		npm_lifecycle_script: string;
		LC_CTYPE: string;
		VSCODE_GIT_IPC_HANDLE: string;
		npm_package_author_email: string;
		npm_package_scripts_lib_helpers: string;
		npm_package_exports___Bz_svelte_types: string;
		npm_package_exports___Earth_svelte_svelte: string;
		npm_package_exports___Lt_svelte_types: string;
		npm_package_exports___Lv_svelte_svelte: string;
		npm_package_exports___ShTa_svelte_types: string;
		npm_package_exports___Soviet_union_svelte_svelte: string;
		SSH_SOCKET_DIR: string;
		npm_package_scripts_package: string;
		npm_package_scripts_gen_docs: string;
		npm_package_exports___Af_svelte_types: string;
		npm_package_exports___EsCt_svelte_types: string;
		npm_package_exports___Gd_svelte_svelte: string;
		npm_package_exports___Kh_svelte_svelte: string;
		npm_package_exports___Mz_svelte_svelte: string;
		npm_package_exports___Nc_svelte_svelte: string;
		npm_package_exports___Ro_svelte_types: string;
		npm_package_exports___Sx_svelte_types: string;
		npm_package_exports___Vc_svelte_types: string;
		npm_package_exports___Zw_svelte_types: string;
		NVM_BIN: string;
		npm_package_exports___Cc_svelte_types: string;
		npm_package_exports___Cm_svelte_svelte: string;
		npm_package_exports___Gw_svelte_types: string;
		npm_package_exports___Gy_svelte_svelte: string;
		npm_package_exports___Ie_svelte_types: string;
		npm_package_exports___Mg_svelte_svelte: string;
		npm_package_exports___Np_svelte_types: string;
		npm_package_exports___Pn_svelte_types: string;
		npm_package_exports___Tr_svelte_types: string;
		npm_package_exports___UsCa_svelte_svelte: string;
		npm_package_exports___UsCo_svelte_types: string;
		npm_package_scripts_copy_package: string;
		npm_package_exports___BqSa_svelte_types: string;
		npm_package_exports___Cn_svelte_svelte: string;
		npm_package_exports___IdJb_svelte_types: string;
		npm_package_exports___Md_svelte_svelte: string;
		npm_package_exports___Mt_svelte_types: string;
		npm_package_exports___Ps_svelte_types: string;
		npm_package_exports___RuCe_svelte_types: string;
		npm_package_exports___RuCu_svelte_svelte: string;
		npm_package_exports___To_svelte_types: string;
		npm_config_user_agent: string;
		GIT_ASKPASS: string;
		VSCODE_GIT_ASKPASS_NODE: string;
		npm_package_devDependencies__playwright_test: string;
		npm_package_exports___AuNsw_svelte_types: string;
		npm_package_exports___Bf_svelte_types: string;
		npm_package_exports___Cc_svelte_svelte: string;
		npm_package_exports___Ec_svelte_types: string;
		npm_package_exports___Fj_svelte_types: string;
		npm_package_exports___Gw_svelte_svelte: string;
		npm_package_exports___Ie_svelte_svelte: string;
		npm_package_exports___Maori_svelte_types: string;
		npm_package_exports___Nato_svelte_types: string;
		npm_package_exports___Np_svelte_svelte: string;
		npm_package_exports___Pn_svelte_svelte: string;
		npm_package_exports___Sa_svelte_types: string;
		npm_package_exports___Tr_svelte_svelte: string;
		npm_package_exports___Us_svelte_types: string;
		npm_package_exports___UsCo_svelte_svelte: string;
		WARP_COMBINED_PROMPT_COMMAND_GRID: string;
		npm_package_scripts_package_publish: string;
		npm_package_exports___Ar_svelte_types: string;
		npm_package_exports___Bs_svelte_svelte: string;
		npm_package_exports___De_svelte_svelte: string;
		npm_package_exports___EcW_svelte_types: string;
		npm_package_exports___EsVariant_svelte_types: string;
		npm_package_exports___RuDpr_svelte_svelte: string;
		npm_package_exports___RuKo_svelte_types: string;
		npm_package_exports___ShAc_svelte_types: string;
		npm_package_exports___ShHl_svelte_types: string;
		npm_package_exports___Sl_svelte_types: string;
		npm_package_exports___St_svelte_svelte: string;
		npm_package_files_0: string;
		npm_package_exports___Ai_svelte_types: string;
		npm_package_exports___Ca_svelte_svelte: string;
		npm_package_exports___Gu_svelte_svelte: string;
		npm_package_exports___Hr_svelte_types: string;
		npm_package_exports___Kikuyu_svelte_types: string;
		npm_package_exports___Kongo_svelte_svelte: string;
		npm_package_exports___Ky_svelte_svelte: string;
		npm_package_exports___Mk_svelte_svelte: string;
		npm_package_exports___Nr_svelte_svelte: string;
		npm_package_exports___Pl_svelte_svelte: string;
		npm_package_exports___Sami_svelte_types: string;
		npm_package_exports___UsMo_svelte_svelte: string;
		CONDA_CHANGEPS1: string;
		npm_package_exports___Be_svelte_svelte: string;
		npm_package_exports___EsCn_svelte_svelte: string;
		npm_package_exports___EsMl_svelte_svelte: string;
		npm_package_exports___Fi_svelte_svelte: string;
		npm_package_exports___Hmong_svelte_types: string;
		npm_package_exports___Icon_svelte_svelte: string;
		npm_package_exports___Id_svelte_types: string;
		npm_package_exports___Jm_svelte_types: string;
		npm_package_exports___Kz_svelte_types: string;
		npm_package_exports___Lk_svelte_svelte: string;
		npm_package_exports___Mh_svelte_types: string;
		npm_package_exports___Ru_svelte_svelte: string;
		npm_package_exports___Sb_svelte_svelte: string;
		npm_package_exports___Wf_svelte_types: string;
		npm_package_exports___Zm_svelte_svelte: string;
		SECURITYSESSIONID: string;
		npm_package_exports___Ai_svelte_svelte: string;
		npm_package_exports___Bb_svelte_types: string;
		npm_package_exports___Eg_svelte_types: string;
		npm_package_exports___Hr_svelte_svelte: string;
		npm_package_exports___InMn_svelte_types: string;
		npm_package_exports___Kikuyu_svelte_svelte: string;
		npm_package_exports___RuBa_svelte_types: string;
		npm_package_exports___Sami_svelte_svelte: string;
		npm_package_exports___Se_svelte_types: string;
		npm_package_exports___Transnistria_svelte_types: string;
		npm_package_scripts_check: string;
		npm_package_exports___Ch_svelte_svelte: string;
		npm_package_exports___EsAr_svelte_svelte: string;
		npm_package_exports___GbOrk_svelte_svelte: string;
		npm_package_exports___Gd_svelte_types: string;
		npm_package_exports___GeAb_svelte_svelte: string;
		npm_package_exports___IdJt_svelte_svelte: string;
		npm_package_exports___In_svelte_svelte: string;
		npm_package_exports___Kh_svelte_types: string;
		npm_package_exports___Kp_svelte_svelte: string;
		npm_package_exports___Mz_svelte_types: string;
		npm_package_exports___Nc_svelte_types: string;
		npm_package_exports___Pe_svelte_svelte: string;
		npm_package_exports___UsHi_svelte_svelte: string;
		COLORTERM: string;
		npm_package_scripts_test_unit: string;
		npm_package_exports___Ae_svelte_types: string;
		npm_package_exports___ChGr_svelte_types: string;
		npm_package_exports___Dj_svelte_types: string;
		npm_package_exports___Fr20r_svelte_types: string;
		npm_package_exports___Gq_svelte_svelte: string;
		npm_package_exports___Kanuri_svelte_svelte: string;
		npm_package_exports___Lr_svelte_types: string;
		npm_package_exports___Mo_svelte_svelte: string;
		npm_package_exports___Ph_svelte_svelte: string;
		npm_package_exports___Tt_svelte_svelte: string;
		npm_package_exports___United_nations_svelte_svelte: string;
		npm_package_exports___Wiphala_svelte_types: string;
		npm_node_execpath: string;
		NODE_ENV: string;
		[key: `PUBLIC_${string}`]: undefined;
		[key: `${string}`]: string | undefined;
	}
}

/**
 * Similar to [`$env/dynamic/private`](https://kit.svelte.dev/docs/modules#$env-dynamic-private), but only includes variables that begin with [`config.kit.env.publicPrefix`](https://kit.svelte.dev/docs/configuration#env) (which defaults to `PUBLIC_`), and can therefore safely be exposed to client-side code.
 * 
 * Note that public dynamic environment variables must all be sent from the server to the client, causing larger network requests — when possible, use `$env/static/public` instead.
 * 
 * Dynamic environment variables cannot be used during prerendering.
 * 
 * ```ts
 * import { env } from '$env/dynamic/public';
 * console.log(env.PUBLIC_DEPLOYMENT_SPECIFIC_VARIABLE);
 * ```
 */
declare module '$env/dynamic/public' {
	export const env: {
		[key: `PUBLIC_${string}`]: string | undefined;
	}
}
